name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Debug - List Files Before Build
        run: |
          echo "Current directory contents:"
          ls -la
          echo "App directory contents:"
          ls -R src/app/

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Debug - List Output Files
        run: |
          echo "Output directory contents:"
          ls -la out/
          echo "Detailed output structure:"
          find out/ -type f

      - name: Copy .nojekyll
        run: touch out/.nojekyll

      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          enable_jekyll: false
          force_orphan: true 